# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
- name: environment
  displayName: environment
  type: string
  default: lab
  values:
  - lab
  - non-prod
  - prod

variables: 
- template: /pipelines/variables/azureinfra-vars-lab.yml
  
stages:
- stage: RG_main
  displayName: Deploy main ResourceGroup
  jobs: 
  - deployment: DeployCommonMain 
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: Main RG Create/Update
            inputs:
              deploymentScope: 'Subscription'
              azureResourceManagerConnection: ${{ variables.armConnection}}
              subscriptionId: ${{ variables.subscriptionId}}
              location: 'Central US'
              templateLocation: 'Linked artifact'
              csmFile: "$(Build.SourcesDirectory)\arm_templates\deploy\rg-deploye.json"
              csmParametersFile: "$(Build.SourcesDirectory)\arm_templates\params\rg-deploy-params.json"
              overrideParameters: -environmentType ${{ parameters.environment }}
              deploymentMode: 'Incremental'
              deploymentName: 'Resource_Group'
 